version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "posts_db"
      POSTGRES_USER: "post_user"
      POSTGRES_PASSWORD: "pgpwd4post"
    ports:
      - "5432:5432"
  # etl:
