version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "posts_db"
      POSTGRES_USER: "post_user"
      POSTGRES_PASSWORD: "pgpwd4post"
    ports:
      - "5432:5432"
    network_mode: host
  extract:
    build:
      context: ./scripts/extract
      dockerfile: Dockerfile
    image: extract_result/latest
    depends_on:
      - db
    network_mode: host
  transform:
    build:
      context: ./scripts/transform
      dockerfile: Dockerfile
    image: transform_result/latest
    depends_on:
      - db
    network_mode: host
